// <auto-generated />
namespace Industrial_tour_reservation_system.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ChangesInBooking : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangesInBooking));
        
        string IMigrationMetadata.Id
        {
            get { return "202205161243172_ChangesInBooking"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
